name: Deploy GitHub Pages

on:
  push:
    branches:
      - trunk

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          yarn
          yarn run build

      - name: Archive
        run: |
          tar --dereference --hard-dereference --directory build/ -cvf artifact.tar .

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: warn

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
