name: Deploy GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - $default-branch

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build
        run: |
          yarn --frozen-lockfile
          yarn run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
